// app/layout.tsx
import type { Metadata } from "next";
import { cookies } from 'next/headers';
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"], weight: "400" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get('theme')?.value || 'light';

  return (
    <html lang="en" className={theme === 'dark' ? 'dark' : ''}>
      <body className={`${nunito.className} antialiased bg-light_theme_body dark:bg-dark_theme_body`}>
        {children}
      </body>
    </html>
  );
}